steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/pragmalogixai/frontend:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_BASE_URL=https://pragmalogixai-backend-eah62ip3iq-uc.a.run.app'
      - '.'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/pragmalogixai/frontend:latest'

options:
  logging: LEGACY
  machineType: 'E2_HIGHCPU_8'
